[context.production.environment]
  HUGO_VERSION = "0.151.0"

[build.environment]
  GO_VERSION = "1.25.1"
  HUGO_VERSION = "0.151.0"
  NODE_VERSION = "22.18.0"
  TZ = "Europe/Oslo"

[build]
  publish = "public"
  command = """\
    git config core.quotepath false && \
    hugo --buildDrafts --gc --minify --baseURL "${URL}"
    """